# Generated by Django 2.2.24 on 2021-09-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0003_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='IDN',
            new_name='dicom_date',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='date',
            new_name='series',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sno',
        ),
        migrations.AddField(
            model_name='upload',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
