# Generated by Django 2.2.24 on 2021-09-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=50)),
                ('IDN', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('tumor', models.CharField(max_length=50)),
            ],
        ),
    ]
