# Generated by Django 2.2.24 on 2021-09-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DICOM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localization',
            name='SUV',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='localization',
            name='IDN',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localization',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localization',
            name='sno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localization',
            name='tumor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localization',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='localization',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='localization',
            name='y',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='localization',
            name='z',
            field=models.IntegerField(null=True),
        ),
    ]
