# Generated by Django 3.2.10 on 2022-03-25 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DICOM', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drugset',
        ),
        migrations.DeleteModel(
            name='Drugsetlog',
        ),
        migrations.DeleteModel(
            name='Examreporttext',
        ),
        migrations.DeleteModel(
            name='Localization',
        ),
        migrations.DeleteModel(
            name='Meditem',
        ),
        migrations.DeleteModel(
            name='Medorder',
        ),
        migrations.DeleteModel(
            name='Visitrecord',
        ),
    ]
