# Generated by Django 2.2.24 on 2021-10-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DICOM', '0003_drugset_drugsetlog_examreporttext_meditem_medorder_visitrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagelocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, db_column='PID', max_length=1000, null=True)),
                ('series', models.CharField(blank=True, db_column='Series', max_length=1000, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=1000, null=True)),
                ('path', models.CharField(blank=True, db_column='Path', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'ImageLocation',
                'managed': False,
            },
        ),
    ]
