# Generated by Django 2.2.24 on 2021-10-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DICOM', '0006_auto_20211008_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Localization',
        ),
        migrations.DeleteModel(
            name='Imagepath',
        ),
    ]
