# Generated by Django 2.2.24 on 2021-10-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DICOM', '0007_auto_20211014_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('pid', models.CharField(blank=True, db_column='PID', max_length=50, null=True)),
                ('sid', models.CharField(blank=True, db_column='SID', max_length=50, null=True)),
                ('sen', models.CharField(blank=True, db_column='SEN', max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('suv', models.CharField(blank=True, db_column='SUV', max_length=50, null=True)),
                ('x', models.CharField(blank=True, max_length=50, null=True)),
                ('y', models.CharField(blank=True, max_length=50, null=True)),
                ('z', models.CharField(blank=True, max_length=50, null=True)),
                ('labelgroup', models.CharField(blank=True, db_column='LabelGroup', max_length=50, null=True)),
                ('labelname', models.CharField(blank=True, db_column='LabelName', max_length=50, null=True)),
                ('labelrecord', models.CharField(blank=True, db_column='LabelRecord', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Localization',
                'managed': False,
            },
        ),
    ]
