# Generated by Django 2.2.24 on 2021-10-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DICOM', '0008_localization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localization',
            options={'managed': True},
        ),
    ]
