# Generated by Django 2.2.24 on 2021-10-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DICOM', '0009_auto_20211014_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localization',
            options={'managed': False},
        ),
    ]
