# Generated by Django 2.2.24 on 2021-09-28 01:47

import Upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=Upload.models.user_directory_path)),
            ],
        ),
        migrations.DeleteModel(
            name='upload',
        ),
    ]
