# Generated by Django 2.2.24 on 2021-09-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0004_auto_20210928_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='series',
        ),
        migrations.AddField(
            model_name='upload',
            name='medicalRecordNumber',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='seriesNumber',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='dicom_date',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='path',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='username',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
